### ISSUE TITLE
Unable to compile when updating elixir 1.4.5 and erlang OTP 20

### ISSUE THREAD

**Issue by technicalcapt** [pvdvreede/pinglix#6] opened 2017-06-26 08:35 UTC
I am unable to compile my application when updating elixir 1.4.5 and erlang/ OTP 20
```
** (CompileError) lib/martide/ping.ex:1: undefined function run_check/1
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```
on
```
$ elixir -v
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.5
```

**Comment by pvdvreede** [comment] 2017-06-28 01:59
I have merged your PR, but am still getting issues - looks like something to do with the Macro injecting the run_check method. So this is still an Issue I will look into.

**Comment by technicalcapt** [comment] 2017-06-28 02:21
@pvdvreede Looks like it's from
```
@dialyzer {:no_match, run_check: 1}
```
I just saw it after update some commits from upstream!

**Comment by technicalcapt** [comment] 2017-06-28 03:21
@pvdvreede Do we need dialyzer here?

**Comment by pvdvreede** [comment] 2017-06-28 05:32
I dont use dialyzer myself but it was added in this commit: https://github.com/pvdvreede/pinglix/commit/5114fce7173766891d0126ef8e63e08ca867b2d7.

I assume it is to be friendly to anyone using this library with dialyzer. I would like it to be friendly with dialyzer, but not knowing much about it perhaps @take-five could shed light on why this is needed and how to fix this issue?

**Comment by take-five** [comment] 2017-06-28 07:37
@technicalcapt @pvdvreede `defcheck` macro generates `run_check/1` function which checks if check result matches against these patterns:
```
case result do
  :ok        -> {:ok, unquote(name)}
  {:ok, m}   -> {:ok, unquote(name), m}
  {:fail, m} -> {:fail, unquote(name), m}
  _          -> {:fail, unquote(name), "Pinglix check does not return the right clause"}
end
```

Now, let's assume that I have the following code:
```elixir
defmodule HealthPlug do
  use Pinglix

  defcheck :database do
    ping_db!
  end

  defp ping_db! do
    DB.select("select 1")
    :ok
  end
```

Dialyzer knows that `result` will always be `:ok` (or will throw an error). With enabled `-no_match` setting Dialyzer will complain that other `case` conditions (`{:ok, _}` and `{:fail, _}`) will never match and should be removed from the code as redundant. To fix this issue I disabled `-no_match` Dialyzer check specifically for generated `run_check/1` function.

I couldn't reproduce an error you refer to (Elixir 1.4.5, OTP 19.3). Does it happen only on OTP 20?

**Comment by take-five** [comment] 2017-06-28 08:02
Ok, I managed to reproduce it on OTP 20, looking into the bug

**Comment by take-five** [comment] 2017-06-28 08:43
PR with fix: https://github.com/pvdvreede/pinglix/pull/8

**Closed as completed** 2017-06-29 22:08 UTC
